### ISSUE TITLE
rclone_upload splitting files

### ISSUE THREAD

**Issue by twshimwell** [mhardcastle/lotss-hba-survey#2]
When using upload_field for very large uv.tar files (say > 300GB) there seems to be issues. SURF have helped  with these but still often encountering problems. I'm wondering if we should consider splitting the uv.tar somehow (thinking about the deep fields particularly). Not sure what the best approach is. Options could be to split off the SOLSDIR (maybe still would be very large tar files though) or to make a uv.tar for each observation ID (so even groups of observation IDs to keep the tar files < say 300GB). Not sure what you think is the most appropriate?

**Comment by mhardcastle** [comment]
I'd be quite reluctant to change the standard now! What are the issues when you have big uploads? I haven't seen this at all.

**Comment by twshimwell** [comment]
Uploads are just that it gets to 100% but then gradually slows down to 0 speed uploading before just starting the upload again from scratch. SURF have increased the timeout so maybe this solves the issue. Currently only seeing it for a 450GB file which is quite a bit deeper than lotss.

**Comment by mhardcastle** [comment]
Well, I guess we could have an option to chunk by obsid if it persists. Wouldn't want to switch that on as the default though because then the LoTSS archive won't be consistent.

**Comment by twshimwell** [comment]
Yeh that might be a good solution and allow us to do the deep fields and things too.

**Comment by mhardcastle** [comment]
OK let me see if I can get a test version of that in place.

**Comment by mhardcastle** [comment]
(I now have this problem too for a 512 GB file! So I have a motivation to fix it (-: )

**Comment by mhardcastle** [comment]
OK after some faffing this works -- rclone_upload.py now takes arguments including a --split_uv which breaks the data and SOLSDIR up by obsid -- or the function has a split_uv argument defaulting to False. In downloading we need to grab all the uv_*.tar files and unpack in the same place. Perhaps Tim you could check out G264-12 which I have just uploaded.
